# Renders `gh issue view --json number,title,body,comments` as a ticket for the agents' prompts.
# Anyone can comment on a public repo, so comments come only from the repo's owners, members and collaborators,
# and from the factory's triage. Triage passes `--arg reporter` to read the reporter's answers to its questions too.
"## Ticket #\(.number): \(.title)\n\n\(.body)\n",
(.comments
  | map(select((.authorAssociation | IN("OWNER", "MEMBER", "COLLABORATOR"))
      or (.author.login == "github-actions" and (.body | startswith("> *This was generated by AI during triage.*")))
      or (.author.login | IN($ARGS.named.reporter // empty))))
  | select(length > 0)
  | "### Comments\n", (.[] | "@\(.author.login) wrote:\n\n\(.body)\n"))
